const TOKEN_META_DATA = [
  {
    updateAuthority: "D5czYVfBn5ktN7QRnhdrPnna1mG1HQHPP6Qv3JQ5pdsA",
    mint: "FPkwvXdbiE1ZWCj7SKj9ixVqgFZKNttzzKNSWVPD6XsK",
    creator: {
      address: "D5czYVfBn5ktN7QRnhdrPnna1mG1HQHPP6Qv3JQ5pdsA",
      verified: 1,
      share: 100,
    },
    primarySaleHappened: 1,
    isMutable: 0,
    editionNonce: 251,
    tokenStandard: 2,
    name: "MuskDonald’s",
    symbol: "MUDO",
    description:
      "MuskDonald’s(MUDO) MuskDonald’s(MUDO) is a joint venture between “ tech billiona ...",
    image: "https://i.imgur.com/wAv1L26.jpeg",
    website: "https://muskdonalds.com/",
    twitter: "https://x.com/cryptol95438655",
    telegram: "https://t.me/+PjNnBSWu2BBiZjI9",
    discord: "",
  },
  {
    updateAuthority: "8JnTdQN55LP1jWtTPvN6bxLpVx7n91Nf2SGJJF1mS9Uc",
    mint: "E8UgrYCiCSJqee8KQ9mCemAMFBE7aN2tZsETKcnupump",
    creator: {
      address: "8JnTdQN55LP1jWtTPvN6bxLpVx7n91Nf2SGJJF1mS9Uc",
      verified: 1,
      share: 100,
    },
    name: "Just a BTC Guy",
    symbol: "BTCGUY",
    primarySaleHappened: 0,
    isMutable: 0,
    editionNonce: 253,
    tokenStandard: 2,
    image:
      "https://gateway.irys.xyz/08P1vZTQSdj7rjFSyPs6LrxAYzGkFLkjDNlKi8IW3sI",
    description:
      "Just a BTC Guy ($BTCGUY) is a token born on Solana Following BTC breaking new Al ...",
    website: "https://www.justabtcguy.com/",
    twitter: "https://t.me/JustaBTCGuy",
    telegram: "https://t.me/JustaBTCGuy",
  },
  {
    updateAuthority: "83yrwvqCLnCn8RFSzRQStmujprDAVHL8tBWy8FhBm5Qu",
    mint: "HBoNJ5v8g71s2boRivrHnfSB5MVPLDHHyVjruPfhGkvL",
    name: "Purple Pepe",
    symbol: "PURPE",
    description:
      " First Pepe created on Solana deployed July 2023. Purple Pepe is the representat ...",
    image: "https://arweave.net/WEugkglBC5LeA8TAuvOv8x2_7wSGDUN2I81_nYp2B-A",
    website: "",
    twitter: "",
    telegram: "",
    primarySaleHappened: 0,
    isMutable: 0,
    editionNonce: 255,
    tokenStandard: 2,
  },
  {
    updateAuthority: "TSLvdd1pWpHVjahSpsvCXUbgwsL3JAcvokwaKt1eokM",
    mint: "2QYmQA5k8dFei18MjoaHocEzStBohFiifdnK2vi2pump",
    name: "Baby Ripple",
    symbol: "BABYXRP",
    uri: "https://ipfs.io/ipfs/Qmc4ts856V9ZJd6vYCdFfUdCzTzxJ7SPSVEoiBEif1PrrX",
    sellerFeeBasisPoints: 0,
    primarySaleHappened: 0,
    isMutable: 0,
    editionNonce: 253,
    tokenStandard: 2,
    description:
      "Missed Ripple $XRP ? Don’t worry, Baby Ripple $BABYXRP is here to give you a sec ...",
    image:
      "https://ipfs.io/ipfs/QmQcCyEdrjjDTSUC7cyUmtif7bXKvwfAHkHER52PWUN4Ak",
    showName: true,
    createdOn: "https://pump.fun",
    twitter: "https://x.com/BabyRippleXRP",
    telegram: "https://t.me/BabyRippleXRP",
    website: "https://babyxrp.xyz",
  },
  {
    key: 4,
    updateAuthority: "TSLvdd1pWpHVjahSpsvCXUbgwsL3JAcvokwaKt1eokM",
    mint: "HgBRWfYxEfvPhtqkaeymCQtHCrKE46qQ43pKe8HCpump",
    name: "Bertram The Pomeranian",
    symbol: "Bert",
    uri: "https://ipfs.io/ipfs/QmNxxaTGgX3sTZV6jTgKyy5a33iFpQMjoWmcFUFfhohw5C",
    sellerFeeBasisPoints: 0,
    primarySaleHappened: 0,
    isMutable: 0,
    editionNonce: 255,
    tokenStandard: 2,
    description:
      "Bert is popular dog with 394k followers on Instagram, that looks like cute bear. ...",
    image:
      "https://ipfs.io/ipfs/Qma4nWagupvZyYG5gRz6WcbCAM8fpzQcSoJWT7ryY82YSg",
    showName: true,
    createdOn: "https://pump.fun",
  },
  {
    updateAuthority: "TSLvdd1pWpHVjahSpsvCXUbgwsL3JAcvokwaKt1eokM",
    mint: "9d24jNVbvHQH3pCB1ZzxRjpFuVV4j1MMJDU3SPxQpump",
    name: "Pudgy Penguins",
    symbol: "PENGU",
    uri: "https://ipfs.io/ipfs/QmWwEBDzhsstk7YxhnKMb5JiMvFKRwr8TYoWQNpDrUMW8A",
    sellerFeeBasisPoints: 0,
    primarySaleHappened: 0,
    isMutable: 0,
    editionNonce: 255,
    tokenStandard: 2,
    description: "Spreading good vibes across the meta 🐧",
    image:
      "https://ipfs.io/ipfs/QmdJLmrEpSu31wYTLKhikxKbL6QGbTLQcyVourWLMszFtL",
    showName: true,
    createdOn: "https://pump.fun",
  },
];

const DEV_TOKEN_META_DATA = [
  {
    updateAuthority: "6dLubMWD7r6bjcw8cMeW5LGdAtXM8Dyi1EscA4ctGc5Y",
    mint: "fFYguHSEEk1cUQs3SMKKTUyoRfQtPLTYvRFCBtnJXgZ",
    name: "Solana Test Token",
    symbol: "STT",
    uri: "https://ipfs.io/ipfs/QmWwEBDzhsstk7YxhnKMb5JiMvFKRwr8TYoWQNpDrUMW8A",
    sellerFeeBasisPoints: 0,
    primarySaleHappened: 0,
    isMutable: 0,
    editionNonce: 255,
    tokenStandard: 2,
    description: "Solana Test Token is just for development 🐧",
    image: "",
    showName: true,
    createdOn: "https://pump.fun",
  },
];

export { TOKEN_META_DATA, DEV_TOKEN_META_DATA };
